name: test
on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:
    branches:
      - master

jobs:
  update-m3u:
    name: update m3u
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run
        shell: pwsh
        run: |
          ./run.ps1
      - name: Commit changes
        run: |
          git config --global user.name "lugw27"
          git config --global user.email "your-email@example.com"
          git commit -m "自动提交更新的文件"
        
      - name: Push changes
        run: |
          git push origin main  
          
