name: update
on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-m3u:
    name: update m3u
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run
        shell: pwsh
        env:
          hkdvb_token: ${{ secrets.HKDVB_TOKEN  }}
        run: |
          ./run.ps1
      - name: push changes
        run: |
          git config --global user.name "lugw27"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -am "自动提交更新的文件"
          git push 
        
 
          
