name: test
on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:
    branches:
      - master

jobs:
  update-m3u:
    name: update m3u
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run
        shell: pwsh
        run: |
          $file='iptv.m3u'
          $new_file="iptv-udpate.m3u"
          $url='https://www.mytvsuper.com.mp/m3u/Live.m3u'
          
          "started"
          test-path $file
          $r=Invoke-RestMethod -Method get -Uri $url
          
          Copy-Item -Path $file -Destination $new_file -Force
          $r|Add-Content -Path $new_file -Force
          
          "end"
          
