name: test
on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:
    branches:
      - master

jobs:
  update-m3u:
    name: update m3u
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run
        shell: pwsh
        env:
          hkdvb_token: ${{ secrets.HKDVB_TOKEN  }}
        run: |
          get-date

 
          
